Portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfols, except: [:show]

  root to: 'pages#home'
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'angular-items', to: 'portfols#angular'

  get 'ruby-on-rails', to: 'portfols#ruby_on_rails'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Portfolio/app/models/portfol.rb
class Portfol < ApplicationRecord

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank? }
  include Placeholder
  validates :title, presence: true
  validates :subtitle, presence: true
  validates :main_image, presence: true
  validates :thumb_image, presence: true

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfols, -> {where(subtitle: "Ruby on Rails")}

  after_initialize :set_default

  def set_default
    self.main_image ||= Placeholder.image_generator(600, 450)
    self.thumb_image ||= Placeholder.image_generator(350, 250)
  end
end

Portfolio/app/controllers/portfols_controller.rb
class PortfolsController < ApplicationController
  before_action :set_portfol, only: [:show, :edit, :destroy, :update]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfols = Portfol.all
  end

  def angular
    @portfols = Portfol.angular
  end

  def ruby_on_rails
    @portfols = Portfol.ruby_on_rails_portfols
  end

  def new
    @portfol = Portfol.new
    3.times { @portfol.technologies.build}
  end

  def create
    @portfol = Portfol.new(portfol_params)

    respond_to do |format|
      if @portfol.save
        format.html { redirect_to portfols_path, notice: 'Your Portfolio item is now live'}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    @portfol = Portfol.find_by_id(params[:id])
  end

  def update
    @portfol = Portfol.find_by(id: params[:id])
    respond_to do |format|
      if @portfol.update(portfol_params)
        format.html { redirect_to portfols_path, notice: 'Your Portfolio item is updated.'}
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfol = Portfol.find_by(id: params[:id])
  end

  def destroy
    @portfol = Portfol.find_by(id: params[:id])
    @portfol.destroy
    respond_to do |format|
      format.html { redirect_to portfols_url, notice: 'Your Item is removed'}
    end

  end

  private
   #need to update
  def set_portfol

  end

  def portfol_params
    params.require(:portfol).permit(:title,
                                    :subtitle,
                                    :body,
                                    :main_image,
                                    :thumb_image,
                                    technologies_attributes: [:name])
  end
end

Portfolio/app/helpers/portfols_helper.rb
module PortfolsHelper
end

Portfolio/app/views/portfols/_form.html.erb
<%= form_for(portfol) do |f|%>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>


  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |tech_form|%>
    <li>
      <%= tech_form.label :name %>
      <%= tech_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>

  <div>
  </div>

<% end %>

Portfolio/app/views/portfols/angular.html.erb
<h1>Angular Portfolio</h1>

<% if logged_in?(:site_admin) %>
<a href="portfols/new">Create New Item</a>
<% end %>

<% @portfols.each do |portfol| %>
  <p><%= link_to portfol.title, portfol_path(portfol) %></p>
  <p><%= portfol.subtitle %></p>
  <p><%= portfol.body %></p>
  <p><%= image_tag(portfol.thumb_image) if portfol.thumb_image%></p>
  <%= link_to "Edit", edit_portfol_path(portfol) if logged_in?(:site_admin)%>
  <%= link_to "Delete", portfol_url(portfol), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin)%>

<% end %>

Portfolio/app/views/portfols/edit.html.erb
<h1>Edit a new Portfolio Item</h1>

<%= render 'form', portfol: @portfol %>

Portfolio/app/views/portfols/index.html.erb
<h1>Portfolio</h1>

<% if logged_in?(:site_admin) %>
<a href="portfols/new">Create New Item</a>
<% end %>

<% @portfols.each do |portfol| %>
  <p><%= link_to portfol.title, portfol_path(portfol) %></p>
  <p><%= portfol.subtitle %></p>
  <p><%= portfol.body %></p>
  <p><%= image_tag(portfol.thumb_image) if portfol.thumb_image%></p>
  <%= link_to "Edit", edit_portfol_path(portfol ) if logged_in?(:site_admin) %>
  <%= link_to "Delete", portfol_url(portfol), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin)%>

<% end %>

Portfolio/app/views/portfols/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= render 'form', portfol: @portfol %>

Portfolio/app/views/portfols/ruby_on_rails.html.erb
<h1>Rails Portfolio</h1>

<a href="portfols/new">Create New Item</a>

<% @portfols.each do |portfol| %>
  <p><%= link_to portfol.title, portfol_path(portfol) %></p>
  <p><%= portfol.subtitle %></p>
  <p><%= portfol.body %></p>
  <p><%= image_tag(portfol.thumb_image) if portfol.thumb_image%></p>
  <%= link_to "Edit", edit_portfol_path(portfol) if logged_in?(:site_admin) %>
  <%= link_to "Delete", portfol_url(portfol), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin)%>

<% end %>

Portfolio/app/views/portfols/show.html.erb
<%= image_tag @portfol.main_image %>

<h1> <%= @portfol.title %></h1>

<em><%= @portfol.subtitle %></em>

<p> <%= @portfol.body %> </p>

<h2>Technology Used:</h2>

<% @portfol.technologies.each do |tech| %>
<p><%= tech.name %></p>
<% end %>


<%= session.inspect %>