Portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfols, except: [:show]

  root to: 'pages#home'
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'angular-items', to: 'portfols#angular'

  get 'ruby-on-rails', to: 'portfols#ruby_on_rails'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Portfolio/app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= @copyright %></p>
  </div>
</footer>

Portfolio/app/views/shared/_application_nav.html.erb
<header>
  <div class="inner">
    <h3 class="masthead-brand">Joungwoo Baik</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class:"nav-link active"%>
      <%= link_to "About Me", pages_about_path, class:"nav-link"%>
      <%= link_to "Contact", pages_contact_path, class:"nav-link"%>
      <%= link_to "Blog", blogs_path, class:"nav-link"%>
      <%= link_to "Portfolio", portfols_path, class:"nav-link"%>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</header>

Portfolio/app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div> <%= link_to "Home", root_path %> </div>
  <div> <%= link_to "About Me", pages_about_path %> </div>
  <div> <%= link_to "Contact", pages_contact_path %> </div>
  <div> <%= link_to "Blog", blogs_path %> </div>
  <div> <%= link_to "Portfolio", portfols_path %> </div>
</div>